apiVersion: v1
kind: ResourceQuota
metadata:
  name: pf-app-quota
  namespace: pf-app-ns
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "3"
    limits.memory: "6Gi"
